Ajout prod compteur linky
bokub/ha-linky pull request #10
Opened 2023-11-10 08:00 UTC by cddu33

Ajout de la récupération des données de productions du compteur linky
Modification des intitulés prm pour prod et conso
Modification de es intitulés token pour prod et conso
Rajout d'un oui/non pour activer les données de protuction ou non

2023-11-11 09:01 UTC, bokub requested changes
Hello, merci pour ta PR !

Je n'ai pas eu le temps de tout lire car je suis en déplacement mais j'ai déjà laissé quelques premiers commentaires

2023-11-11 09:01 UTC, bokub commented on config.yaml
> -  consumption PRM: ''
Sauf erreur de ma part, les personnes qui produisent de l'électricité ont un numéro de PRM dédié à la consommation et un autre dédié à la production, il faudrait donc pouvoir renseigner 2 PRM et 2 tokens

2023-11-11 09:01 UTC, bokub commented on src/config.ts
> +    action: 'yes' | 'non';
Pas de mélange français anglais stp

2023-11-11 09:01 UTC, bokub commented on src/index.ts
> +    let isSyncingNeeded1 = false;
Pas fou comme nom de variable

2023-11-11 09:07 UTC, eco3xfr commented on config.yaml
> -  consumption PRM: ''
Si Vente totale deux Linky donc deux  PMR
Si Vente du surplus même Linky et PRM

2023-11-11 09:53 UTC, bokub commented on config.yaml
> -  consumption PRM: ''
OK !
Dans ce cas il faudrait avoir les 2 champs distincts, quitte à mettre deux fois la même valeur pour ceux qui n'ont qu'un linky

2023-11-11 15:37 UTC, cddu33 commented
Bonsoir, "je vous ai compris " ;)

les modifications demandées sont disponible dans mon dernier PR

2023-11-13 11:57 UTC, bokub requested changes
Merci encore pour tes changements, mais y'a pas mal de points qui m'embêtent, désolé pour les allers-retours je suis assez pris en ce moment je n'ai pas pu tout voir au premier passage

> Bonsoir, "je vous ai compris " ;)

Si c'est une allusion à Charles de Gaulle, je suis pas sûr d'avoir compris ce que ça vient faire là :shrug:

2023-11-13 11:57 UTC, bokub commented on src/config.ts
> +    sync: boolean;
Je trouve que ce paramètre est inutile, on pourrait garder le même fonctionnement qu'avant:
- Si le PRM et le token sont définis, on active la synchronisation, sinon on ne fait rien

2023-11-13 11:57 UTC, bokub commented on config.yaml
> -  consumption name: 'Linky consumption'
Pourquoi avoir viré le name ?

2023-11-13 11:57 UTC, bokub commented on config.yaml
> +  Consumption PRM: ''
Si tu changes le nom des clés, tous les utilisateurs qui ont déjà configuré l'add-on vont se retrouver avec une config invalide au moment de la mise à jour.

C'est pour cette raison que j'avais pris soin de tout préfixer par "consumption" même si la production n'était pas prête

2023-11-13 11:57 UTC, bokub commented on src/index.ts
> +      await haClient.saveStatistics(userConfig.production.prm + 'p', userConfig.production.name, energyData);
Je pense que ce serait plus clean d'ajouter un paramètre "isProd" dans les fonctions de "haClient".

Dans le cas de la production, on pourrait remplacer l'id `linky:12345` par `linky_production:12345` ou un truc du genre

2023-11-13 11:57 UTC, bokub commented on src/index.ts
> +  if (isNewP || isNewC) {
Je comprends pas ta logique, si tu as un nouveau PRM pour la production mais un vieux PRM pour la consommation, tu ré-initialises tout ?

2023-11-13 11:57 UTC, bokub commented on src/linky.ts
> +        offset += interval;
Dommage de tout dupliquer au lieu de factoriser

2023-11-13 11:57 UTC, bokub commented on src/linky.ts
> +          debug(`Cannot fetch daily data comsum from ${from} to ${to}, here is the error:`);
```suggestion
          debug(`Cannot fetch daily consumption data from ${from} to ${to}, here is the error:`);
```

2023-11-13 11:57 UTC, bokub commented on src/linky.ts
> +          debug(`Cannot fetch daily prod data from ${from} to ${to}, here is the error:`);
```suggestion
          debug(`Cannot fetch daily production data from ${from} to ${to}, here is the error:`);
```

2023-11-13 18:46 UTC, cddu33 commented on src/config.ts
> +    sync: boolean;
actuellement l'addon se coupe si pas de prm conso mais maintenant il ne faut pas qu'il se coupe complètement si pas de prm prod donc c'est des changements à faire dans le code

2023-11-13 18:48 UTC, cddu33 commented on config.yaml
> -  consumption name: 'Linky consumption'
oups erreur de ma part

2023-11-13 18:50 UTC, cddu33 commented on config.yaml
> +  Consumption PRM: ''
oui mais c'est dommage de ne pas avoir des noms "propres"

2023-11-13 18:52 UTC, cddu33 commented on src/index.ts
> +  if (isNewP || isNewC) {
non que l'un ou que l'autre , c'est juste que en ligne 117 et ensuite c'est pour éviter de répéter 2 fois le code mais il n'y a bien que l'un ou que l'autre de reset

2023-11-13 18:53 UTC, cddu33 commented on src/linky.ts
> +        offset += interval;
je ne connais pas assez HA, donc n'hésite pas à modifier

2023-11-13 18:54 UTC, cddu33 commented on src/index.ts
> +      await haClient.saveStatistics(userConfig.production.prm + 'p', userConfig.production.name, energyData);
je l'avais créé dans ma première version mais pas vraiment d'intêret

2023-11-14 13:39 UTC, bokub commented
Merci pour toutes ces modifications !

J'essaie de libérer un peu de temps dans les semaines à venir pour faire quelques tests et modifications mais je ne te promets rien :crossed_fingers:

2023-11-14 13:46 UTC, cddu33 commented
En tout cas c'est fonctionnel chez moi

Le mar. 14 nov. 2023, 14:39, Boris K ***@***.***> a écrit :

> Merci pour toutes ces modifications !
>
> J'essaie de libérer un peu de temps dans les semaines à venir pour faire
> quelques tests et modifications mais je ne te promets rien 🤞
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/bokub/ha-linky/pull/10#issuecomment-1810223269>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOE7BOOIXI2OVIUNMELKL6TYENYB5AVCNFSM6AAAAAA7FY2TL2VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQMJQGIZDGMRWHE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-11-14 13:52 UTC, bokub reviewed
Je décommente l'image pour vérifier que ça builde bien

2023-11-14 13:52 UTC, bokub commented on config.yaml
> +#image: ghcr.io/bokub/ha-linky-{arch}
```suggestion
image: ghcr.io/bokub/ha-linky-{arch}
```

2023-11-14 13:52 UTC, bokub commented on config.yaml
> +version: 1.2.8
```suggestion
version: 1.2.0
```

2023-11-15 06:32 UTC, merged

2023-11-15 09:03 UTC, bokub commented
@cddu33 C'est bon, j'ai mergé ce matin + ajouté quelques améliorations et pas mal de refactorisation (cf #11) :partying_face: 

Je vais faire une release dans la journée. Est-ce que c'est toi [cet utilisateur](https://forum.hacf.fr/u/cddu33/summary) sur HACF ?

2023-11-15 09:04 UTC, cddu33 commented
Yep

2023-11-15 09:08 UTC, bokub commented
Super, je ferai également une annonce car beaucoup de personnes attendent cette fonctionnalité. Merci encore pour ton aide !